version: '3'
services:
  mysql:
    image: "mysql:8"
    restart: "unless-stopped"
    environment:
      MYSQL_DATABASE: "mhack"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - "app"


networks:
  app: 
    driver: "bridge"

volumes:
  mysql: null

  root:5qyuQlVLEY6A2DMR